var GAME_LEVELS = [
  ["                                                                                                             xxx x",
   "                                                                                                             x!x x",
   "                                                                                                             x!x x",
   "                                                                                                             x!x x",
   "                                                                                                      o      x!x x",
   "          o      o                          xx    o                o   o                                     x!x x",
   "        xxxx    xxxx  xxxxx               xx     xxx   xxx                                    xxxxxxxxxxxxxxx!!x x",
   "        x!!x    x!!x                    xx       xvx               x   x          xxx     !!!!!!!!!!!!!!!!!!!!xx x",
   "    @   x!!x    x!!x                                         xx  |   |   |                xxxxxxxxxxxxxxxxxxxxx  x",
   "        xvvx    xvvx         xxxx                       xxxxxxx!!!!!!!!!!!xxx                                    x",
   "                   x                                           xxxx!!!!!xxxx                                  x  x",
   "                   xxxxxxxxxxxxxx   xxxxxxxxxxxx     x            xxxxvvxx       xxx         xxx                 x",
   "                       x               v v v v x     x                   x         x         x        x          x",
   "                       x                       x     x                   x         x         x         =         x",
   "                       x                       x     x    x              xx        xx        x         x      x  x",
   "         o        o    x                       xx    x               x   x         x         x    x              x",
   "                       x                       x     x                   x         x         x              x    x",
   "                       x      xxx   xxx        x     x                   x         x        xx      x            x",
   "  xxxx                 x        x   x          x     x        x          x   xxxxxxx         x           x       x",
   "           xxx         x!!!!!!!!x o x          x    xx                   x p x               xx                  x",
   "!!!!!!!!!!!!!x         x!xvx!!!!x   x          x     x                   xxxxx               x         =         x",
   "!!!!!!!!!!!!!x         x!x x!!!!x   x          x     x    x                      xxxxx       x    x              x",
   "!!!!!!!!!!!!!x         x!x x!!!xx o xx! ! ! ! !x     x                     o     xxx         x                x  x",
   "!!!!!!!!!!!!!x         x!x x!!xx     xx x x x xx     xxxxxxxxxxxx   xxxxxxxxxxxxxxxx         x       x           x",
   "!!!!!!!!!!!!!x         x!x x!xx                      x!!v!!!!v!!x                  x         x                   x",
   "!!!!!!!!!!!!!x         x!x x!x    o                xx!!! !!!! !!x               p  x    o    x                   x",
   "!!!!!!!!!!!!!x         xxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxx xxxxxxxxxxxxxxxxxxxxxx         xxxxxxxxxxxxxxx     x",
   "!!!!!!!!!!!!!x                                                                                                  xx",
   "!!!!!!!!!!!!!x                                                                                                 xxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                ",
   "  x     x                                                              o     x  ",
   "  x  @  x                                                    xxxxxxxxxxxx    x  ",
   "  x     x                           o                 xxxxxxxx               x  ",
   "  x     x                          xxxxxxxxxx    xxxxxx      x               x  ",
   "  x     x                     xxxxxx        x!!!!x           x              xx  ",
   "  x     x   x         xxxxxxxxx             xxxxxx           x o  xxx    xxxxx  ",
   "  x     x   xxx                                            xxxxxxxx!xx       x  ",
   "  x     x   xxxxxx                    o                          x!!!x       x  ",
   "  x     x   x    xxxxx                      xxxx                 xx!xx       x  ",
   "  x     x p x        xxxxxxxxx     xxxxx       xxx         xxx    xvxxxxx    x  ",
   "  x     x   x                xxxxxxx             xx      xxx               xxx  ",
   "  x     x   x                                          xxx                   x  ",
   "  x     x   x           o                  o         xxx                     x  ",
   "  x              xxxxx             xxxxxxxxxxx                           xxxxx  ",
   "  x              xxxxx       xx   xx                               o         x  ",
   "  x              xxxxx     xxxx   x         o                    xxxxx       x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                              ",
   "                                 v                                                                            ",
   "                                                                     v                                        ",
   "                                                                                                              ",
   "            v                                                                             v                   ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x               v                     v                               ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                              v     ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                  v                    x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                       v       ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxxvx xvxxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "   @                         xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                 o                     x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x                xxx        x    xxx    x                             x x        xxx          xxx        x  ",
   "  x   o       o    xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x                 x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                         ",
   "                                                                         ",
   "            xxxxxxx      xxx      xx    xx   xxxxxxx                     ",
   "            x           x   x     x x  x x   x                           ",
   "            x   xxx    xxxxxxx    x  xx  x   xxxx                        ",
   "            x     x    x     x    x      x   x                           ",
   "            xxxxxxx    x     x    x      x   xxxxxxx                     ",
   "                                                                         ",
   "                                                                         ",
   "                                                                         ",
   "                                                                         ",
   "                    xxxxxxx   x       x   xxxxxxx    xxxxx               ",
   "                    x     x    x     x    x          x    x              ",
   "                    x     x     x   x     xxxxx      xxxxxx              ",
   "                    x     x      x x      x          x     x             ",
   "                    xxxxxxx       x       xxxxxxx    x      x            ",
   "                                                                         ",
   "                                                                         ",
   "                                                                         ",]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
